package com.wingo.wbase.model;

import java.util.Date;

/**
 * ViewUserInfo generated by MyEclipse Persistence Tools
 */

public class ViewUserInfo implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 4015456165384039696L;

	private ViewUserInfoId id;

	private String account;

	private String userPwd;

	private String userName;

	private String realName;

	private String postNo;

	private String postName;

	private String email;

	private Integer sex;

	private String officeTel;

	private String fax;

	private String phone;

	private String mobile;

	private String address;

	private String zipcode;

	private String picture;

	private String remark;

	private Date createDate;
	
	private Long orgNodeNo;

	private String orgNo;

	private String orgName;

	private Integer isFlag;

	private String roleNo;

	// Constructors

	/** default constructor */
	public ViewUserInfo() {
	}

	/** full constructor */
	public ViewUserInfo(String account, String userPwd, String userName,
			String realName, String postNo, String postName, String email,
			Integer sex, String officeTel, String fax, String phone,
			String mobile, String address, String zipcode, String picture,
			String remark, Date createDate, Long orgNodeNo, String orgNo, String orgName,
			Integer isFlag, String roleNo) {
		this.account = account;
		this.userPwd = userPwd;
		this.userName = userName;
		this.realName = realName;
		this.postNo = postNo;
		this.postName = postName;
		this.email = email;
		this.sex = sex;
		this.officeTel = officeTel;
		this.fax = fax;
		this.phone = phone;
		this.mobile = mobile;
		this.address = address;
		this.zipcode = zipcode;
		this.picture = picture;
		this.remark = remark;
		this.createDate = createDate;
		this.orgNodeNo = orgNodeNo;
		this.orgNo = orgNo;
		this.orgName = orgName;
		this.isFlag = isFlag;
		this.roleNo = roleNo;
	}

	// Property accessors

	public ViewUserInfoId getId() {
		return this.id;
	}

	public void setId(ViewUserInfoId id) {
		this.id = id;
	}

	public Long getOrgNodeNo() {
		return orgNodeNo;
	}

	public void setOrgNodeNo(Long orgNodeNo) {
		this.orgNodeNo = orgNodeNo;
	}

	public String getRoleNo() {
		return roleNo;
	}

	public void setRoleNo(String roleNo) {
		this.roleNo = roleNo;
	}

	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public Integer getIsFlag() {
		return isFlag;
	}

	public void setIsFlag(Integer isFlag) {
		this.isFlag = isFlag;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getOfficeTel() {
		return officeTel;
	}

	public void setOfficeTel(String officeTel) {
		this.officeTel = officeTel;
	}

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getOrgNo() {
		return orgNo;
	}

	public void setOrgNo(String orgNo) {
		this.orgNo = orgNo;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPicture() {
		return picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public String getPostName() {
		return postName;
	}

	public void setPostName(String postName) {
		this.postName = postName;
	}

	public String getPostNo() {
		return postNo;
	}

	public void setPostNo(String postNo) {
		this.postNo = postNo;
	}

	public String getRealName() {
		return realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getSex() {
		return sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPwd() {
		return userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	public String getZipcode() {
		return zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

}