package com.wingo.wbase.model;

/**
 * WbaseSysNavigation generated by MyEclipse Persistence Tools
 */

public class WbaseSysNavigation implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1290415313324489372L;

	private String id;

	private String navName;

	private String navLink;

	private Integer navOpen;

	private Integer navFlag;

	// Constructors

	/** default constructor */
	public WbaseSysNavigation() {
	}

	/** full constructor */
	public WbaseSysNavigation(String navName, String navLink, Integer navOpen,
			Integer navFlag) {
		this.navName = navName;
		this.navLink = navLink;
		this.navOpen = navOpen;
		this.navFlag = navFlag;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNavName() {
		return this.navName;
	}

	public void setNavName(String navName) {
		this.navName = navName;
	}

	public String getNavLink() {
		return this.navLink;
	}

	public void setNavLink(String navLink) {
		this.navLink = navLink;
	}

	public Integer getNavOpen() {
		return this.navOpen;
	}

	public void setNavOpen(Integer navOpen) {
		this.navOpen = navOpen;
	}

	public Integer getNavFlag() {
		return this.navFlag;
	}

	public void setNavFlag(Integer navFlag) {
		this.navFlag = navFlag;
	}

}