package com.wingo.wbase.model;

import java.util.Date;

/**
 * WbaseRoleObj generated by MyEclipse Persistence Tools
 */

public class WbaseRoleObj implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 4600882178166457261L;

	private String id;

	private String objNo;

	private String objType;

	private String roleNo;

	private Date createDate;

	// Constructors

	/** default constructor */
	public WbaseRoleObj() {
	}

	/** minimal constructor */
	public WbaseRoleObj(String objNo, String objType, String roleNo) {
		this.objNo = objNo;
		this.objType = objType;
		this.roleNo = roleNo;
	}

	/** full constructor */
	public WbaseRoleObj(String objNo, String objType, String roleNo,
			Date createDate) {
		this.objNo = objNo;
		this.objType = objType;
		this.roleNo = roleNo;
		this.createDate = createDate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getObjNo() {
		return this.objNo;
	}

	public void setObjNo(String objNo) {
		this.objNo = objNo;
	}

	public String getObjType() {
		return this.objType;
	}

	public void setObjType(String objType) {
		this.objType = objType;
	}

	public String getRoleNo() {
		return this.roleNo;
	}

	public void setRoleNo(String roleNo) {
		this.roleNo = roleNo;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}