package com.wingo.wbase.model;

import java.util.Date;

/**
 * WbaseOrg generated by MyEclipse Persistence Tools
 */

public class WbaseOrg implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 8107835543991565510L;

	private String id;
	
	private Long nodeNo;

	private String orgNo;

	private String orgName;

	private Integer orgLevel;

	private Long subNodeNo;

	private String remark;

	private Integer isFlag;

	private Integer viewOrder;

	private Date createDate;

	// Constructors

	/** default constructor */
	public WbaseOrg() {
	}

	/** minimal constructor */
	public WbaseOrg(Long nodeNo,String orgNo, String orgName, Integer orgLevel,
			Long subNodeNo, Integer isFlag, Integer viewOrder) {
		this.nodeNo = nodeNo;
		this.orgNo = orgNo;
		this.orgName = orgName;
		this.orgLevel = orgLevel;
		this.subNodeNo = subNodeNo;
		this.isFlag = isFlag;
		this.viewOrder = viewOrder;
	}

	/** full constructor */
	public WbaseOrg(Long nodeNo,String orgNo, String orgName, Integer orgLevel,
			Long subNodeNo, String remark, Integer isFlag, Integer viewOrder,
			Date createDate) {
		this.nodeNo = nodeNo;
		this.orgNo = orgNo;
		this.orgName = orgName;
		this.orgLevel = orgLevel;
		this.subNodeNo = subNodeNo;
		this.remark = remark;
		this.isFlag = isFlag;
		this.viewOrder = viewOrder;
		this.createDate = createDate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Long getNodeNo() {
		return nodeNo;
	}

	public void setNodeNo(Long nodeNo) {
		this.nodeNo = nodeNo;
	}

	public String getOrgNo() {
		return orgNo;
	}

	public void setOrgNo(String orgNo) {
		this.orgNo = orgNo;
	}

	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public Integer getOrgLevel() {
		return this.orgLevel;
	}

	public void setOrgLevel(Integer orgLevel) {
		this.orgLevel = orgLevel;
	}

	public Long getSubNodeNo() {
		return subNodeNo;
	}

	public void setSubNodeNo(Long subNodeNo) {
		this.subNodeNo = subNodeNo;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getIsFlag() {
		return this.isFlag;
	}

	public void setIsFlag(Integer isFlag) {
		this.isFlag = isFlag;
	}

	public Integer getViewOrder() {
		return this.viewOrder;
	}

	public void setViewOrder(Integer viewOrder) {
		this.viewOrder = viewOrder;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}