package com.wingo.wbase.model;

/**
 * WbaseResource generated by MyEclipse Persistence Tools
 */

public class WbaseResource implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 3679288294598284785L;

	private String id;

	private Long nodeNo;

	private String resNo;

	private String resName;

	private Integer resLevel;

	private Long subNodeNo;

	private String resPath;

	private String resPic;

	private String remark;

	private Integer isFlag;

	private Integer viewOrder;

	private Integer isTarget;

	// Constructors

	/** default constructor */
	public WbaseResource() {
	}

	/** minimal constructor */
	public WbaseResource(String resName, Integer resLevel, Long subNodeNo,
			Integer isFlag, Integer viewOrder, Integer isTarget) {
		this.resName = resName;
		this.resLevel = resLevel;
		this.subNodeNo = subNodeNo;
		this.isFlag = isFlag;
		this.viewOrder = viewOrder;
		this.isTarget = isTarget;
	}

	/** full constructor */
	public WbaseResource(Long nodeNo, String resNo, String resName,
			Integer resLevel, Long subNodeNo, String resPath, String resPic,
			String remark, Integer isFlag, Integer viewOrder, Integer isTarget) {
		this.nodeNo = nodeNo;
		this.resNo = resNo;
		this.resName = resName;
		this.resLevel = resLevel;
		this.subNodeNo = subNodeNo;
		this.resPath = resPath;
		this.resPic = resPic;
		this.remark = remark;
		this.isFlag = isFlag;
		this.viewOrder = viewOrder;
		this.isTarget = isTarget;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Long getNodeNo() {
		return this.nodeNo;
	}

	public void setNodeNo(Long nodeNo) {
		this.nodeNo = nodeNo;
	}

	public String getResNo() {
		return this.resNo;
	}

	public void setResNo(String resNo) {
		this.resNo = resNo;
	}

	public String getResName() {
		return this.resName;
	}

	public void setResName(String resName) {
		this.resName = resName;
	}

	public Integer getResLevel() {
		return this.resLevel;
	}

	public void setResLevel(Integer resLevel) {
		this.resLevel = resLevel;
	}

	public Long getSubNodeNo() {
		return this.subNodeNo;
	}

	public void setSubNodeNo(Long subNodeNo) {
		this.subNodeNo = subNodeNo;
	}

	public String getResPath() {
		return this.resPath;
	}

	public void setResPath(String resPath) {
		this.resPath = resPath;
	}

	public String getResPic() {
		return this.resPic;
	}

	public void setResPic(String resPic) {
		this.resPic = resPic;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getIsFlag() {
		return this.isFlag;
	}

	public void setIsFlag(Integer isFlag) {
		this.isFlag = isFlag;
	}

	public Integer getViewOrder() {
		return this.viewOrder;
	}

	public void setViewOrder(Integer viewOrder) {
		this.viewOrder = viewOrder;
	}

	public Integer getIsTarget() {
		return this.isTarget;
	}

	public void setIsTarget(Integer isTarget) {
		this.isTarget = isTarget;
	}

}