package com.wingo.wbase.model;

/**
 * WbaseSysShortcut generated by MyEclipse Persistence Tools
 */

public class WbaseSysShortcut implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 2968809708585750805L;

	private String id;

	private String cutUid;

	private Long cutNodeNo;

	private Integer cutOrder;

	// Constructors

	/** default constructor */
	public WbaseSysShortcut() {
	}

	/** full constructor */
	public WbaseSysShortcut(final String cutUid, final Long cutNodeNo, final Integer cutOrder) {
		this.cutUid = cutUid;
		this.cutNodeNo = cutNodeNo;
		this.cutOrder = cutOrder;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(final String id) {
		this.id = id;
	}

	public String getCutUid() {
		return this.cutUid;
	}

	public void setCutUid(final String cutUid) {
		this.cutUid = cutUid;
	}

	public Long getCutNodeNo() {
		return this.cutNodeNo;
	}

	public void setCutNodeNo(final Long cutNodeNo) {
		this.cutNodeNo = cutNodeNo;
	}

	public Integer getCutOrder() {
		return this.cutOrder;
	}

	public void setCutOrder(final Integer cutOrder) {
		this.cutOrder = cutOrder;
	}

}