package com.wingo.wbase.model;

import java.util.Date;

/**
 * WbaseOrgUser generated by MyEclipse Persistence Tools
 */

public class WbaseOrgUser implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -8426435837657923178L;

	private String id;

	private String userAccount;

	private Long orgNodeNo;

	private Date createDate;

	// Constructors

	/** default constructor */
	public WbaseOrgUser() {
	}

	/** minimal constructor */
	public WbaseOrgUser(String userAccount, Long orgNodeNo) {
		this.userAccount = userAccount;
		this.orgNodeNo = orgNodeNo;
	}

	/** full constructor */
	public WbaseOrgUser(String userAccount, Long orgNodeNo, Date createDate) {
		this.userAccount = userAccount;
		this.orgNodeNo = orgNodeNo;
		this.createDate = createDate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount;
	}

	public Long getOrgNodeNo() {
		return this.orgNodeNo;
	}

	public void setOrgNodeNo(Long orgNodeNo) {
		this.orgNodeNo = orgNodeNo;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}