package com.wingo.wbase.model;

import java.util.Date;

/**
 * WbaseUser generated by MyEclipse Persistence Tools
 */

public class WbaseUser implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1010575764215390511L;

	private String id;

	private String account;

	private String userPwd;

	private String userName;

	private String realName;

	private String email;

	private Integer sex;

	private String officeTel;

	private String fax;

	private String phone;

	private String mobile;

	private String address;

	private String zipcode;

	private String picture;

	private String remark;

	private Date createDate;

	private Integer isFlag;

	// Constructors

	/** default constructor */
	public WbaseUser() {
	}

	/** minimal constructor */
	public WbaseUser(String account, String userPwd, String userName,
			Integer isFlag) {
		this.account = account;
		this.userPwd = userPwd;
		this.userName = userName;
		this.isFlag = isFlag;
	}

	/** full constructor */
	public WbaseUser(String account, String userPwd, String userName,
			String realName, String email, Integer sex, String officeTel,
			String fax, String phone, String mobile, String address,
			String zipcode, String picture, String remark, Date createDate,
			Integer isFlag) {
		this.account = account;
		this.userPwd = userPwd;
		this.userName = userName;
		this.realName = realName;
		this.email = email;
		this.sex = sex;
		this.officeTel = officeTel;
		this.fax = fax;
		this.phone = phone;
		this.mobile = mobile;
		this.address = address;
		this.zipcode = zipcode;
		this.picture = picture;
		this.remark = remark;
		this.createDate = createDate;
		this.isFlag = isFlag;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public String getOfficeTel() {
		return this.officeTel;
	}

	public void setOfficeTel(String officeTel) {
		this.officeTel = officeTel;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getIsFlag() {
		return this.isFlag;
	}

	public void setIsFlag(Integer isFlag) {
		this.isFlag = isFlag;
	}

}