package com.wingo.wbase.model;

/**
 * WbaseSysCompany generated by MyEclipse Persistence Tools
 */

public class WbaseSysCompany implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 8058843097038475605L;

	private String id;

	private String comName;

	private String comLogo;

	private String comRemark;

	// Constructors

	/** default constructor */
	public WbaseSysCompany() {
	}

	/** full constructor */
	public WbaseSysCompany(String comName, String comLogo, String comRemark) {
		this.comName = comName;
		this.comLogo = comLogo;
		this.comRemark = comRemark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getComName() {
		return this.comName;
	}

	public void setComName(String comName) {
		this.comName = comName;
	}

	public String getComLogo() {
		return this.comLogo;
	}

	public void setComLogo(String comLogo) {
		this.comLogo = comLogo;
	}

	public String getComRemark() {
		return this.comRemark;
	}

	public void setComRemark(String comRemark) {
		this.comRemark = comRemark;
	}

}