package com.wingo.wbase.model;

import java.util.Date;

/**
 * WbasePost generated by MyEclipse Persistence Tools
 */

public class WbasePost implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 579737650869262568L;

	private String id;

	private String postNo;

	private String postName;

	private Integer postLevel;

	private String remark;

	private Date createDate;

	// Constructors

	/** default constructor */
	public WbasePost() {
	}

	/** minimal constructor */
	public WbasePost(String postNo, String postName, Integer postLevel) {
		this.postNo = postNo;
		this.postName = postName;
		this.postLevel = postLevel;
	}

	/** full constructor */
	public WbasePost(String postNo, String postName, Integer postLevel,
			String remark, Date createDate) {
		this.postNo = postNo;
		this.postName = postName;
		this.postLevel = postLevel;
		this.remark = remark;
		this.createDate = createDate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPostNo() {
		return this.postNo;
	}

	public void setPostNo(String postNo) {
		this.postNo = postNo;
	}

	public String getPostName() {
		return this.postName;
	}

	public void setPostName(String postName) {
		this.postName = postName;
	}

	public Integer getPostLevel() {
		return this.postLevel;
	}

	public void setPostLevel(Integer postLevel) {
		this.postLevel = postLevel;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}